# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rt9JZnaGRuRx1cWj9HLx-ha3Yw-g78d1
"""

import streamlit as st
from wordcloud import WordCloud
import matplotlib.pyplot as plt

# 使用函數封裝原始邏輯
def run_analysis(keyword, period):
    # 假設這裡是您的爬蟲和分析代碼
    # 返回分析結果和文字雲數據
    result = {"關鍵字": keyword, "期間": period, "分析狀態": "完成"}
    word_freq = {"示例詞1": 50, "示例詞2": 30}
    return result, word_freq

# Streamlit 應用邏輯
st.title("熱門關鍵字分析")
keyword = st.text_input("請輸入關鍵字：")
period = st.number_input("請輸入搜尋期間（月）", min_value=1, value=3)

if st.button("開始分析"):
    result, word_freq = run_analysis(keyword, period)
    st.json(result)

    # 顯示文字雲
    wordcloud = WordCloud(width=800, height=400, background_color="white").generate_from_frequencies(word_freq)
    plt.imshow(wordcloud, interpolation="bilinear")
    plt.axis("off")
    st.pyplot(plt)